appstory3/urls.py
from django.urls import path, include
from . import views

app_name = 'appstory3'
urlpatterns = [
    path('', views.project, name = 'project'),
]

jadwal/urls.py
from django.urls import path, include
from . import views

app_name = 'jadwal'
urlpatterns = [
    path('', views.add, name = 'add'),
    path('view', views.view, name = 'view'),
    path('detail/<id>', views.detail, name = 'detail'),
    path('delete/<id>', views.delete, name = 'delete'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

story1/urls.py
from django.urls import path, include
from . import views

app_name = 'story1'
urlpatterns = [
    path('', views.home, name = 'home'),
    path('about', views.about, name= 'about'),
    path('education', views.education, name = 'education'),
]

story3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story1.urls')),
    path('appstory3/', include('appstory3.urls')),
    path('jadwal/', include('jadwal.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('accounts/', include('story9.urls'), name='accounts'),
    path('accounts/', include('django.contrib.auth.urls'))

]

story7/urls.py
from django.urls import path, include
from . import views

app_name = 'story7'
urlpatterns = [
    path('', views.accordion, name="accordion"),
]

story8/urls.py
from django.urls import path, include
from . import views

app_name = 'story8'
urlpatterns = [
    path('', views.buku, name="buku"),
    path('data/', views.data, name="data"),
]

story9/urls.py
from django.urls import path
from story9.views import SignUpView
from . import views

app_name = 'story9'

urlpatterns = [
    path('masuk', views.masuk, name='masuk/'),
    path('login/', views.login, name='login'),
    path('logout', views.logout, name='logout/'),
    path('signup', SignUpView.as_view(), name='signup'),
]

appstory3/models.py
from django.db import models

# Create your models here.

jadwal/models.py
from django.db import models

# Create your models here.
class Sched(models.Model):
    Subject = models.CharField(max_length = 60)
    Lecturer = models.CharField(max_length = 60)
    Credit = models.CharField(max_length = 60)
    Description = models.TextField(max_length = 60)
    Semester = models.CharField(max_length = 60)
    Room = models.CharField(max_length = 60, default = "Online Class")

main/models.py
from django.db import models

# Create your models here.

story1/models.py
from django.db import models

# Create your models here.

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

jadwal/forms.py
from django import forms

from .models import Sched

class Matkul(forms.ModelForm):
    class Meta:
        model = Sched
        fields = ['Subject', 'Lecturer', 'Credit', 'Description', 'Semester', 'Semester', 'Room']
        widgets = {
            'Subject' : forms.TextInput(attrs = {'class':'form-control'}),
            'Lecturer' : forms.TextInput(attrs = {'class':'form-control'}),
            'Credit' : forms.TextInput(attrs = {'class':'form-control'}),
            'Description' : forms.TextInput(attrs = {'class':'form-control'}),
            'Semester' : forms.TextInput(attrs = {'class':'form-control'}),
            'Room' : forms.TextInput(attrs = {'class':'form-control'}),
        }

appstory3/views.py
from django.shortcuts import render

# Create your views here.
def project(request):
    return render(request, 'project.html')

jadwal/views.py
from django.shortcuts import render, redirect
from .models import Sched
from .forms import Matkul

# Create your views here.
def add(request):
    if request.method == 'POST':
        form = Matkul(request.POST)
        if form.is_valid():
            sched = form.save()
            sched.save()
            return redirect('jadwal:view')
    else:
        form = Matkul()
    return render(request, 'add.html', {'form': form})
def view(request):
    jadwal = Sched.objects.order_by('Subject')
    return render(request, 'view.html', {'jadwal':jadwal})
def detail(request, id):
    detail = Sched.objects.get(id=id)
    return render(request, 'detail.html', {'detail':detail})
def delete(request, id):
    Sched.objects.get(id = id).delete()
    return redirect('jadwal:view')

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/home.html')

story1/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'home.html')
def about(request):
    return render(request, 'home.html#about')
def education(request):
    return render(request, 'home.html#education')

story7/views.py
from django.shortcuts import render

# Create your views here.
def accordion(request):
    return render (request, 'accordion.html')

story8/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
import requests
import json

# Create your views here.
def buku(request):
    return render(request, 'books.html')

def data(request):
    arg = request.GET['q']
    url = 'https://www.googleapis.com/books/v1/volumes?q=' + arg
    req = requests.get(url)
    data = json.loads(req.content)
    return JsonResponse(data, safe=False)

story9/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, auth

# Create your views here.

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

def masuk(request):
    return render(request, "home.html")

def login(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            auth.login(request,user)
            return redirect('/home.html')
    else:
        form = AuthenticationForm()
        return render(request, 'login.html', {'form': form})

def logout(request):
    logout(request)
    return redirect('/')

appstory3/templates/project.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Arnindya Zhavira</title>
    <link rel="shortcut icon" href="{% static 'img/Title_IMG.png' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

    {% block content %}
<body>
    <style>
        body {
            background-image: url("/static/img/test2.png");
        }
    </style>
    <div class="projects">
        <img src="{% static 'img/sosbg.png' %}">
        <img src="{% static 'img/sosbg10.png' %}">
        <img src="{% static 'img/sosbg12.png' %}">
    </div>
    <div class="projects2">
        <img src="{% static 'img/sosbg3.png' %}">
        <img src="{% static 'img/sosbg4.png' %}">
        <img src="{% static 'img/sosbg7.png' %}">
        <img src="{% static 'img/story9.png' %}">
    </div>
    <div class="projects3">
        <img src="{% static 'img/one.png' %}">
        <img src="{% static 'img/three.png' %}">
    </div>
</body>
    {% endblock content %}

</html>

jadwal/templates/add.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Arnindya Zhavira</title>
    <link rel="shortcut icon" href="{% static 'img/Title_IMG.png' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <style>
        body {
            background-image: url("bg_body.png");
        }
    </style>
</head>
    {% block content %}
<body>
    <div class="addsched">
        <p>ADD SCHEDULE</p>
    <form method="POST">
        {% csrf_token %}
        <div class="mr-auto ml-auto" style="width:50%;">
            {% for i in form %}
                <div class="form-group">
                    {{ i.label_tag }}
                    {{ i }}
                </div>
            {% endfor %}
        <br>
        <div class="container">
            <button type="submit">Submit</button>
        </div>
        </div>
    </div>

    </form>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
    {% endblock content %}
</html>

jadwal/templates/detail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Arnindya Zhavira</title>
    <link rel="shortcut icon" href="{% static 'img/Title_IMG.png' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <style>
        body {
            background-image: url("bg_body.png");
        }
    </style>
</head>
    {% block content %}
<body>
    <div class="detail"></div>
        <p>DETAIL</p>
        <br>
        <p style="font-size: 20px;">Subject : {{ detail.Subject }}</p>
        <br>
        <table class="table table-bordered">
            <thead>
            <tr>
                <th scope="col">Lectures</th>
                <td>{{ detail.Lecturer }}</td>
            </tr>
            <tr>
                <th scope="col">Number of Credits</th>
                <td>{{ detail.Credit }}</td>
            </tr>
            <tr>
                <th scope="col">Semester</th>
                <td>{{ detail.Semester }}</td>
            </tr>
            <tr>
                <th scope="col">Room</th>
                <td>{{ detail.Room }}</td>
            </tr>
            </thead>
            <tbody>


            </tbody>
        </table>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
    {% endblock content %}
</html>
    

jadwal/templates/view.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Arnindya Zhavira</title>
    <link rel="shortcut icon" href="{% static 'img/Title_IMG.png' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <style>
        body {
            background-image: url("bg_body.png");
        }
    </style>
</head>
    {% block content %}
<body>
    <p style="color: white; font-family: ;">SCHEDULE</p>
    <br>
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope = "col">Subject</th>
            <th scope = "col">Lecturer</th>
            <th scope = "col">Number of Credits</th>
            <th scope = "col">Description</th>
            <th scope = "col">Semester</th>
            <th scope = "col">Room</th>
            <th scope = "col">Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for sched in jadwal %}
        <tr>
            <td>
                <a href="{% url 'jadwal:detail' id=sched.id %}">{{ sched.Subject }}</a>
            </td>
            <td>
                {{ sched.Lecturer }}
            </td>
            <td style="text-align: center;">
                {{ sched.Credit}}
            </td>
            <td>
                {{ sched.Description }}
            </td>
            <td>
                {{ sched.Semester }}
            </td>
            <td>
                {{ sched.Room }}
            </td>
            <td>
                <a class="btn" style="background-color: goldenrod; color: white;" href="{% url 'jadwal:delete' id=sched.id %}" role="button">Delete</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
    {% endblock content %}
</html>

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <p><img src="{% static 'img/django-logo-negative.svg' %}"></p>
{% endblock content %}

story1/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  {% block meta %}
  {% endblock meta %}
</head>

{% block navbar %}
<body>
  <nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand logo custom-margin" href="#">arnindyazvr</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto custom-margin">
            <a class="nav-link nav-links" href="{% url 'story1:home' %}">Home</a>
            <a class="nav-link nav-links" href="{% url 'story1:about' %}">About</a>
            <a class="nav-link nav-links" href="{% url 'story1:education' %}">Education</a>
            <a class="nav-link nav-links " href="{% url 'appstory3:project' %}">Project</a>
            <a class="nav-link nav-links " href="{% url 'jadwal:add' %}">Schedule</a>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle nav-links" href="#" id="dropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Activity
              </a>
              <div class="dropdown-menu dropdown-style" aria-labelledby="dropdownMenuLink" style="background-color:#a4b9f0f9;">
                <a class="dropdown-item" href="{% url 'story7:accordion' %}" style="color: white;">Accordion</a>
                <a class="dropdown-item" href="{% url 'story8:buku' %}" style="color: white;">Books</a>
              </div>
        </div>
        {% if user.is_authenticated %}
        <a class="nav-link" style="color: white;" href="{% url 'logout' %}">Log Out</a>
        {% else %}
        <a class="nav-link" style="color: white;" href="{% url 'story9:signup' %}">Sign Up</a>
        <a class="nav-link" style="color: white;" href="{% url 'login' %}">Log In</a>
        {% endif %}

    </div>
  </nav>
{% endblock navbar %}

  {% block content %}
  {% endblock content %}
</body>

</html>

story1/templates/home.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Arnindya Zhavira</title>
    <link rel="shortcut icon" href="{% static 'img/Title_IMG.png' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
    {% block content %}
<body>
    {% if user.is_authenticated %}
        <div id="grad1">
            <div class="center-content">
                <h2>Hi {{ user }}! Welcome to my page</h2><br></br>
                <h3>Find Me on</h3><br>
                <div class="social-media">
                    <a href="https://www.instagram.com/arnindyazhavira/" class="fa fa-instagram"></a>
                    <a href="https://www.linkedin.com/in/arnindya-zhavira-454955173/" class="fa fa-linkedin"></a>
                </div>
            </div>
        </div>
    
    {% else %}

    <style>
    body {
        background-image: url("bg_body.png");
    }
    </style>
    <section>
        <!--text--->
            <div class="text-container">
                    <p>Hello,</p>
                    <p>I'm Arnin</p>
                    <p>Welcome to my first website, take your time and enjoy the visit!</p>
            </div>
    </section>
    <div class="about-container" id="about">
    <!--img-->
        <img src="{% static 'img/model.png' %}">
    <!--about-me-text-->
    <div class="col-md-6">
        <div class="about-text">
            <p>A Little Bit About Me</p>
            <p>Hi! My name is Arnindya Zhavira, people usually call me Arnin. 
                I am currently a sophomore at University of Indonesia majoring in Computer Science. 
                Besides academic-related things i love to cook, i’m also a mother of 10 cats and i love them so much!</p>
        </div>
    </div>
    </div>
<!--Education-->
    <div class="education" id="education">
        <!--text-->
        <div class="education-text ">
    <p>Educational Background</p>
            </div>
        <div class="box-container">
            <!--1------------->
                <div class="box-1">
                <p class="heading">SMPN 19 Jakarta</p>
                <p class="details">year: 2013 - 2016</p>
                </div>
            <!--2------------->
                <div class="box-2">
                <p class="heading">SMAN 70 Jakarta</p>
                <p class="details">year: 2016 - 2019</p>
                </div>
            <!--3------------->
                <div class="box-3">
                <p class="heading">Universitas Indonesia</p>
                <p class="details">year: 2019 - present</p>
                </div>
            </div>
        </div>
    <!--footer--------------->
 <footer class="footer">
    <!--heading-->
 <p>Reach Me!</p>
    <!--social-->
   <div class="social-icons">
    <a href="https://wa.me/081805170869"><img class="social-icons" src="{% static 'img/wa-logo.png' %}"/></a>
    <a href="https://www.instagram.com/arnindyazhavira/"><img class="social-icons" src="{% static 'img/ig_logo.png' %}"/></a>
    <a href="https://www.twitter.com/arnindyaazvr/"><img class="social-icons" src="{% static 'img/twitter_logo.png' %}"/></a>
   </div>
</footer>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    {% endif %}
</body>
        {% endblock content %}
</html>

story7/templates/accordion.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <title>Story 7</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/accordion.css' %}"> 
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
    crossorigin="anonymous"></script>
    {% endblock %}
</head>
<body>
    {% block content %}
    <button class="accordion">Current Activities</button>
    <div class="panel">
        <p>Hidup tugas pacil</p>
    </div>

    <button class="accordion">Achievements</button>
    <div class="panel">
        <p>Pernah juara 1 lomba nyanyi :)</p>
    </div>

    <button class="accordion">Experiences</button>
    <div class="panel">
        <p>Panitia SETARA SMAN 70 Jakarta</p>
        <p>Staff of Partnership COMPFEST 12</p>
        <p>Staff of Business Development PERAK</p>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        var acc = document.getElementsByClassName("accordion");
        var i;
        
        for (i = 0; i < acc.length; i++) {
          acc[i].addEventListener("click", function() {
            this.classList.toggle("active");
            var panel = this.nextElementSibling;
            if (panel.style.maxHeight) {
              panel.style.maxHeight = null;
            } else {
              panel.style.maxHeight = panel.scrollHeight + "px";
            } 
          });
        }
    </script>
    
</body>
{% endblock %}
</html>

story8/templates/books.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <title>Story 8</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/books.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
    crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    {% endblock %}
    
</head>
<body>

    {% block content %}
    <p><i class="fas fa-search"></i> Search
        <input id="keyword" class="form-control" placeholder="Enter keyword" style="width: 15%;">
    </p><br>

    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th scope="col">Book Title</th>
                <th scope="col">Cover</th>
                <th scope="col">Author</th>
            </tr>
            </thead>
            <tbody id="hasil">
            
            </tbody>
        </table>
    </div>

    <script type="text/javascript" src="{% static 'js/books.js' %}"></script>
    {% endblock %}
    
</body>
</html>

story9/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}
<title>log in</title>
<link rel="stylesheet" href="{% static 'css/login.css' %}"> 
{% endblock head %}


{% block content %}

<div>
  {% if user.is_authenticated %}
    <h3 class="title3" style="margin-top:4vw;">Yay you're logged in!</h3>
  
  {% else %}
  <div class="main">
      <h3 class="title" style="margin-top:4vw;">Log In</h3>
  </div><br>
  <div class="login-page">
    
    <div class="login-form" >
      <form action="{% url 'login' %}" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" value="Login" style="color:white ; background-color: #a4b9f0f9;">Sign Up</button>
      </form>
    </div>
    
  </div>
  {% endif %}
    
</div>

{% endblock content %}

story9/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block head %}
<title>sign up</title>
<link rel="stylesheet" href="{% static 'css/login.css' %}"> 
{% endblock head %}


{% block content %}

  {% if user.is_authenticated %}
    <h3 class="title3" style="margin-top:4vw;">Yay you're logged in!</h3>
    
  {% else %}
    <div class="main">
      <h3 class="title" style="margin-top:4vw;">Sign Up</h3>
    </div><br>

    <div class="signup-page">

      <div class="signup-form">
        <form method="POST">
          {% csrf_token %}
          {{ form|crispy }}
          <button type="submit" value="Login" style="color:white ; background-color: #a4b9f0f9;">Sign Up</button>
        </form>
      </div>

    </div>

  {% endif %}


{% endblock content %}